name: Clippy Linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  clippy:
    name: Clippy on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Run clippy via make
        run: make clippy
