name: Clippy Linter

on:
  pull_request:
    branches: [master]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
    - name: Run clippy
      run: cargo clippy --all-targets -- -D warnings
