name: Clippy Linter

on:
push:
  branches: [master]
  pull_request:
    branches: [master]

jobs:
  clippy:
  strategy:
    matrix:
      os: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings
