name: Deploy Rust Docs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build Rust documentation
        run: cargo doc --no-deps -p quantbr

       - name: Prepare doc output
        run: |
          # Remove arquivos ou pastas indesejadas do output do Rustdoc
          rm -rf ./target/doc/quantbr/roadmap

          # Cria pasta para publicar
          mkdir -p ./doc_publish

          # Copia o conteúdo limpo do Rustdoc
          cp -r ./target/doc/quantbr/. ./doc_publish/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc_publish
          publish_branch: gh-pages
          force_orphan: true
          cname: quantbr.com
          